form-maker/FFF-BE

src/main/java/com/formmaker/fff/common/response/ResponseMessage.java
src/main/java/com/formmaker/fff/user/User.java
src/main/java/com/formmaker/fff/user/UserController.java
src/main/java/com/formmaker/fff/user/UserRepository.java
src/main/java/com/formmaker/fff/user/UserService.java
src/main/java/com/formmaker/fff/user/request/UserSignupRequest.java

- 기본 회원가입 구현 
- ResponseMessage  Getter 어노테션 추가 
- User 엔티티 코드 추가 
- UserController 생성 및 코드 추가 
- UserRepository 생성 및 코드 추가
- UserService 생성 및 코드 추가 
- UserSignupRequest 생성 및 코드 추가 
close #4

✨ feat: 기본 회원가입 구현

---

.github/workflows/gradle.yml
appspec.yml
build.gradle
scripts/start.sh
scripts/stop.sh

✨ Feat : CI/CD 환경 설정

---

.github/workflows/gradle.yml

♻️ Refactor : CI/CD 리팩토링

---

.github/workflows/gradle.yml

♻️ Refactor : git action 시크릿 프로퍼티 설정 추가

---

src/main/java/com/formmaker/fff/FffApplication.java
src/main/java/com/formmaker/fff/answer/request/AnswerCreateRequest.java
src/main/java/com/formmaker/fff/common/TimeStamped.java
src/main/java/com/formmaker/fff/common/response/DataPageResponse.java
src/main/java/com/formmaker/fff/common/response/PageStatusResponse.java
src/main/java/com/formmaker/fff/common/type/SortTypeEnum.java
src/main/java/com/formmaker/fff/question/request/QuestionCreateRequest.java
src/main/java/com/formmaker/fff/survey/Survey.java
src/main/java/com/formmaker/fff/survey/SurveyController.java
src/main/java/com/formmaker/fff/survey/SurveyService.java
src/main/java/com/formmaker/fff/survey/request/SurveyCreateRequest.java
src/main/java/com/formmaker/fff/survey/response/SurveyMainResponse.java
src/main/java/com/formmaker/fff/user/UserService.java

메인 페이지내의 전체 설문 내용 반환 구현
- Page Form 제작
- Page Status 제작
- 정렬 기준 구현
- 조회 기능 구현
close #13
요청
응답

✨ Feat : 메인페이지 설문 조회 구현

---

src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/type/SocialTypeEnum.java
src/main/java/com/formmaker/fff/user/OauthService.java
src/main/java/com/formmaker/fff/user/User.java
src/main/java/com/formmaker/fff/user/UserController.java
src/main/java/com/formmaker/fff/user/UserRepository.java

카카오 소셜 로그인 구현 및 기존 회원 연결
- OauthService 코드 추가
- 기존 동일 Email이 존재할 경우 해당 계정과 연결
- kakao 회원가입
close #31

✨Feat : 카카오 로그인 구현

---

src/main/java/com/formmaker/fff/survey/SurveyController.java
src/main/java/com/formmaker/fff/survey/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/SurveyService.java
src/main/java/com/formmaker/fff/survey/response/SurveyMyResponse.java

- 마이페이지 설문 조회 기능
- surveyController 코드 추가
- surveyMyResponse 생성
- surveyService 코드 추가
- surveyRepository 코드추가 
close #33

✨Feat: 마이페이지 조회 기능

---

src/main/java/com/formmaker/fff/reply/Reply.java
src/main/java/com/formmaker/fff/reply/ReplyRepository.java
src/main/java/com/formmaker/fff/reply/ReplyService.java
src/main/java/com/formmaker/fff/survey/SurveyController.java
src/main/java/com/formmaker/fff/survey/SurveyService.java
src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
src/main/java/com/formmaker/fff/survey/request/ReplyRequest.java

- List 로 받는 Rank 를 변환하여 저장을 하는데 이 형태는 지속적으로 더 나은 방법을 찾아봐야할 것 같습니다! (Json  문자열 형태 등)
close #40

✨ Feat : 설문 응답 등록 API 구현

---

src/main/java/com/formmaker/fff/common/type/AnswerTypeEnum.java
src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
src/main/java/com/formmaker/fff/common/type/StatusTypeEnum.java
src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/request/SurveyCreateRequest.java
src/main/java/com/formmaker/fff/survey/response/SurveyMainResponse.java
src/main/java/com/formmaker/fff/survey/response/SurveyMyResponse.java
src/main/java/com/formmaker/fff/survey/response/SurveyReadResponse.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

회의에 따른 설문의 상태 컬럼 변경
기존 Survey의 상태값인 isDone(Boolean) 컬럼을 status(Enum)으로 변경
기존 사용되던 isDone 부분을 전부 수정
status 컬럼이 사용되는 Response Dto 수정
close #45

✨Feat : 설문 상태 컬럼 수정

---

src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/type/StatusTypeEnum.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/request/ReplyCreateRequest.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/request/SurveyCreateRequest.java
src/main/java/com/formmaker/fff/survey/response/SurveyMainResponse.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

- Survey entity 컬럼 추가 및 삭제
- Survey service 코드 간소화
- surveyCreateRequest 요구 사항에 맞춰 수정
- Survey service -> createSurvey 메서드 엔티티 요구사항에 맞춰 수정
close #46

♻️ Refactor : 설문 시작 지점 수정

---

src/main/java/com/formmaker/fff/answer/entity/Answer.java
src/main/java/com/formmaker/fff/answer/request/AnswerCreateRequest.java
src/main/java/com/formmaker/fff/answer/response/AnswerResponse.java
src/main/java/com/formmaker/fff/question/controller/QuestionController.java
src/main/java/com/formmaker/fff/question/entity/Question.java
src/main/java/com/formmaker/fff/question/request/QuestionCreateRequest.java
src/main/java/com/formmaker/fff/question/response/QuestionResponse.java
src/main/java/com/formmaker/fff/question/service/QuestionService.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

summary 컬럼 추가
minValue, maxValue -> volume 컬럼으로 변경
컬럼 추가 및 컬럼 변경
컬럼 변경사항에 따른 기존 이용부분 수정
answer Entity내에 data컬럼 answerValue로 변경
close #49

♻️Refactor : 설문 문제 컬럼 변경

---

build.gradle
src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
src/main/java/com/formmaker/fff/common/type/SocialTypeEnum.java
src/main/java/com/formmaker/fff/user/controller/UserController.java
src/main/java/com/formmaker/fff/user/entity/User.java
src/main/java/com/formmaker/fff/user/request/SocialUserInfoDto.java
src/main/java/com/formmaker/fff/user/service/GoogleService.java

구글로그인 구현
- GoogleService 생성
- SocialUserInfoDto생성
- User 엔티티 @빌더 추가  socialUpdate / return this 추가
- UserController 코드 추가 
close #39

✨Feat: 구글 로그인 구현

---

src/main/java/com/formmaker/fff/common/type/SortTypeEnum.java
src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

설문 조회 정렬 기준 수정
정렬 타입 Enum 수정
수정에 따른 isAsc 삭제
close #50

♻️Refactor : 설문 조회 수정

---

src/main/java/com/formmaker/fff/survey/service/SurveyService.java

♻️ Refactor : Entity 대신 Entity Dto 를 사용하도록 로직 변경

---

src/main/java/com/formmaker/fff/user/controller/UserController.java

♻️ Refactor : OAuth 로그인 Url 명세와 맞게 수정

---

src/main/java/com/formmaker/fff/FffApplication.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java

자정마다 진행되는 설문의 상태 업데이트 기능 추가
Scheduler 작성
update 쿼리 작성
close #79

✨Feat : 자정 설문 상태 업데이트 기능 추가

---

build.gradle
src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
src/main/java/com/formmaker/fff/reply/dto/request/ReplyCreateRequest.java
src/main/java/com/formmaker/fff/reply/dto/request/ReplyDto.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

- Integer 타입의 value 를 하나의 컬럼에서 관리하도록 수정
- Json 형식의 문자열을 db에 String 타입으로 저장할 수 있도록 함
- String 타입인 Json 형식 문자열을 JsonObject 으로 변환
close #68

♻️ Refactor : Reply Entity 컬럼 수정 및 내부로직 변경

---

build.gradle
src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
src/main/java/com/formmaker/fff/sse/CustomEmitter.java
src/main/java/com/formmaker/fff/sse/controller/SseController.java
src/main/java/com/formmaker/fff/sse/repository/EmitterRepository.java
src/main/java/com/formmaker/fff/sse/repository/EmitterRepositoryImpl.java
src/main/java/com/formmaker/fff/sse/service/NotificationService.java

SSE활용 실시간 설문 참가 인원 조회
참가마다 값이 수정되는 특성으로 캐시 시용X
현재 sse연결이 끊어진 시점을 체크하지 못하므로 값이 계속해서 오르는 현상 발생
이후 프론트와 같이 작업 후 시점 체크 필요
SSE 구현
설문 참가 시 sse Event생성
close #90

✨Feat : 실시간 참가 인원 조회 기능 추가

---

build.gradle
src/main/java/com/formmaker/fff/stats/controller/StatsController.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

현재 응답 관련하여 전체 파일 다운로드 기능 추가
Reply 데이터 CSV 변환
각 Type에 맞게 CSV 변환
LoginId 가림 처리
빈 응답 데이터에 대한 공간 조정
변환 데이터 다운 기능 추가
close #94

✨Feat : 설문 응답 파일 다운로드 기능 추가

---

build.gradle
src/main/java/com/formmaker/fff/common/config/SwaggerConfig.java
src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/resources/application.properties

swagger 추가
swaggerConfig 추가
swagger url 오픈
close #98

✨Feat : swagger 추가

---

src/main/java/com/formmaker/fff/survey/dto/response/SurveyMainResponse.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

메인페이지에 사용되는 문항수, 소요 시간 필드 추가
이후 처리 응답 시간에 따른 평균 시간 변경 필요
totalQuestion 필드 추가
totalTime 필드 추가
close #99

♻️Refactor : 메인페이지 필드 추가

---

src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/dto/response/SurveyMyResponse.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

마이페이지에서 요청한 필드 추가
startedAt 추가
endedAt 추가
deadLine 삭제
achievementRate 연산 및 추가
설문의 상태(Status)에 따른 응답
close #100

♻️Refactor : 마이 페이지 필드 수정

---

src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
src/main/java/com/formmaker/fff/reply/dto/request/ReplyRequest.java
src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java

설문 응답에 따른 로직 추가
설문 응답 시 설문에 참여자수 증가(participant)
close #101

♻️Refactor

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java

통계 처리 코드 최적화
불필요한 코드 삭제
stream문 이용
close #111

♻️Refactor : 통계 코드 최적화

---

src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/stats/dto/DailyParticipant.java
src/main/java/com/formmaker/fff/stats/dto/StatsResponse.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

설문의 시작일부터 종료일까지의 참가자 수 통계
설문의 생성일(createdAt) 필드 추가
최대 답장 질문 추출
답장기준 응답자수 날짜별로 정리
close #108

✨Feat : 날짜별 참가자 수 통계 기능 추가

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/dto/DescriptiveResponse.java

주관식 장문형에 대한 응답
총 응답 개수 3개와 현재 응답 간의 조절
랜덤 장문형 값 반환
close #115

✨Feat : 설문 주관식 장문형 조회 기능 추가

---

src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
src/main/java/com/formmaker/fff/stats/controller/StatsController.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

요청한 날짜에 따른 통계 조회 기능 추가
start와 end 기간에 따른 조건 추가
start와 end가 비어있을 때에 대한 처리
close #118

✨Feat : 날짜별 통계 조회 기능 추가

---

src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/question/service/QuestionService.java

♻️ Refactor: 설문 조회 필드 추가

---

build.gradle
src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/mail/config/MailConfig.java
src/main/java/com/formmaker/fff/mail/controller/MailController.java
src/main/java/com/formmaker/fff/mail/entity/EmailAuth.java
src/main/java/com/formmaker/fff/mail/repository/EmailAuthRepository.java
src/main/java/com/formmaker/fff/mail/service/MailService.java
src/main/java/com/formmaker/fff/user/service/UserService.java

✨ Feat : 이메일 인증 API 구현

---

build.gradle
src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/question/service/QuestionService.java

✨Feat: RDS연결

---

src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/dto/response/MyPageResponse.java

♻️Refactor : MyPage Response 수정

---

build.gradle
src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/question/service/QuestionService.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

♻️ Refactor: 설문 진행 중인 설문만 표시

---

src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/stats/dto/StatsResponse.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

프론트와 연결중 API설계도에서 작성한 변수와 오차 수정
날짜별 참가자 수 API 설계도에 맞춰 dailyParticipants에서 dailyParticipantList로 변경
설문 질문 API 설계도에 맞춰 summary에서 questionSummary로 변경

♻️Refactor : 날짜별 참가자수 필드, 설문 질문 필드 수정

---

src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/stats/dto/StatsResponse.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

Question Request 필드 수정
목표달성율 수정
close #

♻️Refactor : 필드 수정

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/common/response/security/UserDetailsImpl.java
src/main/java/com/formmaker/fff/common/response/security/UserDetailsServiceImpl.java

요청 URL 허용 
비회원 설문 응답 허용
파일 다운로드 허용
close #

♻️Refactor : url 허용 수정

---

src/main/java/com/formmaker/fff/participant/Participant.java
src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java

유저의 설문 참가 여부를 위한 테이블 추가
테이블 추가
날짜별 참가자 수 통계 로직 변경
설문 등록 중복 처리
close #134

✨Feat : 설문 참가 테이블 추가

---

src/main/java/com/formmaker/fff/user/service/UserService.java

♻️ Refactor : 회원가입 성공 시, 만료시간이 지나지않은 인증코드 redis 에서 삭제

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/sse/CustomEmitter.java
src/main/java/com/formmaker/fff/sse/controller/SseController.java
src/main/java/com/formmaker/fff/sse/repository/EmitterRepository.java
src/main/java/com/formmaker/fff/sse/repository/EmitterRepositoryImpl.java
src/main/java/com/formmaker/fff/sse/service/NotificationService.java

기존 sse 로직 개서
사용자의에게 각 세션마다 주어지는 시간을 기준으로  sseEmitter 관리
redis 연결
close #139

♻️Refactor : SSE 로직 개선

---

src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/type/StatusTypeEnum.java
src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

- 설문 삭제 , 타입 변경 DELETE로 분류하는 것으로 변경 
- 삭제된 설문 조회시 에러코드 추가
- 설문 삭제 , 타입 변경 DELETE로 분류하는 것으로 변경 
- 삭제된 설문 조회시 에러코드 추가
close #146

♻️Refactor: 삭제 타입 변경으로, 변경

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java

♻️ Refactor : 헤더에 담긴 리프레쉬 토큰에 접근할 수 있도록 설정

---

src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
src/main/java/com/formmaker/fff/common/redis/RedisUtil.java
src/main/java/com/formmaker/fff/user/service/UserService.java

♻️Refactor: 리프레쉬 토큰 레디스 적용

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java

♻️ Refactor: 허가수정

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java

♻️ Refactor : certbot 요청 인가 거절 이슈 - 방안1

---

src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
src/main/java/com/formmaker/fff/question/entity/Question.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

빈값에 대한 유효성 검사
각 타입에 따른 null값 확인
타입에 따른 AnswerList 확인
예외 처리
close #147

♻️Refactor : 설문 생성 유효성 검사

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/controller/StatsController.java
src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

통계 로직 개선 및 필요 기능 추가
각 통계 로직 개선
통계 정렬 추가
통계 권한 추가
close #152

♻️Refactor : 통계 개선

---

src/main/java/com/formmaker/fff/question/dto/response/QuestionNavigationResponse.java
src/main/java/com/formmaker/fff/survey/dto/response/SurveyReadResponse.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

설문 응답 시 질문 네비게이션을 위한 데이터 응답
ResponseDto 생성
설문 응답 수정
close #168

✨Feat : 설문 응답 질문 정보 추가

---

src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java

♻️Refactor: 엑세스토큰 시간수정

---

src/main/java/com/formmaker/fff/gift/dto/request/GiftCreateRequest.java
src/main/java/com/formmaker/fff/gift/dto/response/GiftResponse.java
src/main/java/com/formmaker/fff/gift/entity/Gift.java
src/main/java/com/formmaker/fff/gift/giftRepository/GiftRepository.java
src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/dto/request/SurveyCreateRequest.java
src/main/java/com/formmaker/fff/survey/dto/response/SurveyMainResponse.java
src/main/java/com/formmaker/fff/survey/dto/response/SurveyReadResponse.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java
src/main/java/com/formmaker/fff/user/controller/UserController.java

✨Feat : 선물 폼 추가

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/common/exception/CustomAuthenticationEntryPoint.java
src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
src/main/java/com/formmaker/fff/common/response/security/UserDetailsImpl.java
src/main/java/com/formmaker/fff/participant/Participant.java
src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/stats/controller/StatsController.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java
src/main/java/com/formmaker/fff/user/repository/UserRepository.java

비회원 설문 응답에 따른 UUID 발급 및 응답 중복 처리
UUID 발급 및 혹시 모를 중복 처리
UUID 쿠키 저장 및 가져오기
Reply 로직 변경
설문 상태에 따른 조희 로직 변경
비 로그인 및 잘못된 토큰 예외처리
close #167

✨Feat : 비회원 설문 응답 로직 추가

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/dto/DescriptiveList.java
src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java

♻️ Refactor : 주관식 서술형, 전체 응답 데이터 반환로직 추가

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java

♻️ Refactor : https 프론트 도메인 cors 설정

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/dto/DescriptiveList.java

♻️ Refactor: 단답형 수정

---

src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java

♻️ Refactor : D-Day 컬럼 삭제 및 D-Day 계산 로직 추가

---

build.gradle
src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
src/main/java/com/formmaker/fff/stats/controller/StatsController.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java

xlsx 다운로드 기능 추가
다운로드 이메일 필드 추가
권한 설정
close #178

✨Feat : xlsx 다운로드 기능 추가

---

src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
src/main/java/com/formmaker/fff/user/controller/UserController.java

기존 jwt 인증 방식 수정
비 인증 api에 대한 처리
close #188

♻️Refactor : JWT 인증 방식 수정

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

통계 정렬 수정 및 오류 수정
주관식 단문형 정렬 수정
랭크 통계 정렬 기준 수정
저장 시 특수문자 sheetName 오류 수정
close #191

♻️Refactor : 정렬 수정 및 저장 오류 수정

---

src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java

♻️ Refactor: 토큰 시간 수정

---

src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/type/SortTypeEnum.java
src/main/java/com/formmaker/fff/mail/controller/MailController.java
src/main/java/com/formmaker/fff/mail/service/MailService.java
src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java

- 마감된 설문에 대한 알림을 설문 제작자의 이메일로 발송
- ex) 매일 오전 8:30 에 전날 마감된 설문을 찾아 메일 발송 (30일에 발송된 메일은 29일에 끝난 설문에 대한 안내 메일)
- scheduled 어노테이션으로 매일 오전 8:30 마다 로직 실행
close #190

✨ Feat : 마감된 설문 안내 메일 발송

---

src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

개인 정보 등 추가 동의사항을 위한 폼 추가
Enum 변경
응답 저장 틀 추가
Status 함수 추가
Status  제외
close #199

✨Feat : 동의 폼 추가

---

src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
src/main/java/com/formmaker/fff/question/entity/Question.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java

동의 폼 다운로드 형식 추가 및 question의 summary 크기 수정
추가된 동의 폼에 따른 다운로드 형식 추가
summary의 length를 255(default) -> 500

✨Feat : 동의 폼 다운로드 추가 및 필드 크기 수정

---

src/main/java/com/formmaker/fff/user/controller/UserController.java
src/main/java/com/formmaker/fff/user/service/UserService.java

♻️ Refactor: 아이디 중복체크 수정

---

src/main/java/com/formmaker/fff/reply/entity/Reply.java

♻️ Refactor 서술형 응답 글자수 500 자로 변경

---

src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java

설문 done 업데이트 날짜 기준을 이전 날짜로,
상태에 따른 업데이트 로직
업데이트 날짜 기준 상태 로직 추가
업데이트 기준 날짜를 하루 전으로
close #202

♻️Refactor : 설문 상태 업데이트 로직 수정

---

src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java

sse 테스트를 위한 오픈
securityConfig 수정

♻️Refactor : uri 오픈

---

src/main/java/com/formmaker/fff/mail/controller/MailController.java
src/main/java/com/formmaker/fff/mail/service/MailService.java

♻️ Refactor : 이메일 형식의 값이 아닐 때, 인증번호 발송 실패 응답 발송하도록 에러처리

---

src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/question/entity/Question.java
src/main/java/com/formmaker/fff/question/service/QuestionService.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

✨ Feat: 설문 문제 필수응답 유무 체크

---

src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
src/main/java/com/formmaker/fff/question/service/QuestionService.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/survey/dto/response/SurveyReadResponse.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

- 설문 조회시 전체 응답자 표기
- surveyReadResponse 에 participant 추가 및 관련 로직 수정
- QuestionResponse 에 participant 추가 및 관련 로직 수정 
close #208

♻️ Refactor: 설문 조회시 전체 응답자 표기

---

src/main/java/com/formmaker/fff/mail/service/MailService.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java
src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

♻️ Refactor : Survey -> User 단방향 연관관계 설정과 그에 따라 코드 수정

---

src/main/java/com/formmaker/fff/common/exception/CustomAuthenticationEntryPoint.java
src/main/java/com/formmaker/fff/common/exception/CustomValidException.java
src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
src/main/java/com/formmaker/fff/common/exception/GlobalExceptionHandler.java
src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
src/main/java/com/formmaker/fff/question/entity/Question.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
src/main/java/com/formmaker/fff/survey/dto/request/SurveyCreateRequest.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

- 설문 제작시 설문 제목 , 설문 설명이 공란이면 예외처리 / 문항 추가 후 선택 항목 생성 안 할시에 유효성 검사 
close #217

♻️ Refactor: 설문 제작시 설문 타이틀 및 설명 유효성 검사 , 문항 유무 유효성 검사

---

src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
src/main/java/com/formmaker/fff/user/controller/RefreshController.java
src/main/java/com/formmaker/fff/user/service/UserService.java

♻️ Refactor: 리프레쉬토큰 수정

---

src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java

refactor: 토큰테스트

---

src/main/java/com/formmaker/fff/stats/StatsMethod.java
src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java

통계시 slide부분에 필요한 라벨 추가
response 필드 추가
필드 수정 로직 추가
close #232

✨Feat : slide 통계 라벨추가

---

src/main/java/com/formmaker/fff/common/aop/timer/ExecutionTimer.java
src/main/java/com/formmaker/fff/sse/controller/SseController.java
src/main/java/com/formmaker/fff/sse/service/NotificationService.java

SSE 로직 변경
Join API 삭제 및 해당 관련 로직 connect에 통합

♻️Refactor : SSE API 통합

---

src/main/java/com/formmaker/fff/reply/service/ReplyService.java

♻️ Refactor: 응답시 update문 발생 수정

---

src/main/java/com/formmaker/fff/common/aop/timer/ExecutionTimer.java
src/main/java/com/formmaker/fff/participant/Participant.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
src/main/java/com/formmaker/fff/stats/controller/StatsController.java
src/main/java/com/formmaker/fff/stats/service/StatsService.java
src/main/java/com/formmaker/fff/survey/entity/Survey.java

기존 다운로드 로직의 불필요한 쿼리 최적화
쿼리 수정
로직 변경
타이머 체크
close #229
최적화 전
최적화 후

♻️Refactor : 다운로드 로직 최적화

---

src/main/java/com/formmaker/fff/answer/repositoy/AnswerRepository.java
src/main/java/com/formmaker/fff/gift/giftRepository/GiftRepository.java
src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
src/main/java/com/formmaker/fff/question/repository/QuestionRepository.java
src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
src/main/java/com/formmaker/fff/reply/entity/Reply.java
src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
src/main/java/com/formmaker/fff/reply/service/ReplyService.java
src/main/java/com/formmaker/fff/survey/service/SurveyService.java

- 설문 삭제 타입 변환에서 삭제로 로직 수정
close #55 
전 ( 응답 30개 기준 )
후 ( 응답 30개 기준 )

♻️ Refactor: 설문 삭제 로직 수정 
